apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:20.04
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: config-volume
          mountPath: /home/solana/genesis
          # subPath: genesis.bin
  volumes:
    - name: config-volume
      configMap:
        name: genesis-config